In [1]:
mytuple = ('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight')

In [2]:
del mytuple[0]

TypeError: 'tuple' object doesn't support item deletion

In [3]:
mytuple[0] = 1

TypeError: 'tuple' object does not support item assignment

In [ ]:
del mytuple 

In [4]:
mytuple

('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight')

In [5]:
for i in mytuple:
    print(i, end = '  ')

one  two  three  four  five  six  seven  eight  

In [6]:
for i in enumerate(mytuple):
    print(i, end = '  ')

(0, 'one')  (1, 'two')  (2, 'three')  (3, 'four')  (4, 'five')  (5, 'six')  (6, 'seven')  (7, 'eight')  

In [7]:
mytuple1 = ('one', 'two', 'three', 'four', 'one', 'one', 'two', 'three')

In [11]:
mytuple1.count('one')

3

In [12]:
mytuple1.count('two')

2

In [13]:
mytuple.count('four')

1

In [14]:
#tuple üyelik (membership) operasyonları 
'one' in mytuple

True

In [15]:
'ten' in mytuple

False

In [16]:
if 'three' in mytuple:
    print('yes')
else:
    print('no')

yes


In [17]:
if 'eleven' in mytuple:
    print('yes')
else:
    print('no')

no


In [18]:
mytuple

('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight')

In [19]:
#dizin (index) pozisyonu
mytuple.index('one')

0

In [20]:
mytuple.index('five')

4

In [21]:
mytuple1

('one', 'two', 'three', 'four', 'one', 'one', 'two', 'three')

In [22]:
mytuple1.index('one')

0

In [23]:
mytuple2 = (43, 67, 99, 12, 6, 90, 67)

In [24]:
sorted(mytuple2) #yeni bir sıralanmış liste geriye döner ve orjinal tuple üzerinde herhangi bir değişiklik oluşmaz

[6, 12, 43, 67, 67, 90, 99]

In [25]:
sorted(mytuple2, reverse = True) #azalan (descending) sırada sıralama yapar

[99, 90, 67, 67, 43, 12, 6]

In [26]:
def main():
    name_list = []
    
    again = 'y'
    
    while again == 'y':
        name = input('Bir isim giriniz: ')
        
        name_list.append(name)
        
        print('Başka bir isim eklemek ister misiniz?')
        again = input('y = evet, herhangi başka bir şey = hayır: ')
        print()
        
    print('Yazdığınız isimler şu şekildedir')
    
    for name in name_list:
        print(name)
    
main()

Bir isim giriniz: Ahmet
Başka bir isim eklemek ister misiniz?
y = evet, herhangi başka bir şey = hayır: y

Bir isim giriniz: Fatma
Başka bir isim eklemek ister misiniz?
y = evet, herhangi başka bir şey = hayır: y

Bir isim giriniz: Hüseyin
Başka bir isim eklemek ister misiniz?
y = evet, herhangi başka bir şey = hayır: y

Bir isim giriniz: Ayşe
Başka bir isim eklemek ister misiniz?
y = evet, herhangi başka bir şey = hayır: bitir hoca

Yazdığınız isimler şu şekildedir
Ahmet
Fatma
Hüseyin
Ayşe


In [27]:
#list comprehensions
#yeni listeler oluşturmak için ilgi çekici bir yol sağlar
#for ifadesinden önce hesaplanacak ifadeyi kapsayan köşeli parantezli yapılardır. Sıfır ya da daha fazla if ifadesi içerirler.

In [29]:
mystring = "WELCOME"
mylist = [i for i in mystring]
print(mylist)

['W', 'E', 'L', 'C', 'O', 'M', 'E']


In [30]:
mylist1 = [i for i in range(40) if i % 2 == 0]
mylist1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [31]:
mylist1 = [i for i in range(40) if i % 2 == 1]
mylist1

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]

In [32]:
mylist3 = [num**2 for num in range(10)]
mylist3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [33]:
list1 = [2, 3, 4, 5, 6, 7]
list1 = [i*10 for i in list1]
list1

[20, 30, 40, 50, 60, 70]

In [34]:
mylist4 = [i for i in range(200) if i % 3 == 0 if i % 9 == 0 if i % 12 == 0]
mylist4

[0, 36, 72, 108, 144, 180]

In [36]:
L1 = [print("{} is Even Number".format(i)) if i % 2 == 0 else print("{} is Odd Number".format(i)) for i in range(10)]

0 is Even Number
1 is Odd Number
2 is Even Number
3 is Odd Number
4 is Even Number
5 is Odd Number
6 is Even Number
7 is Odd Number
8 is Even Number
9 is Odd Number


In [37]:
mystr = "One 1 two 2 three 3 four 4 five 5 six 6789"
numbers = [i for i in mystr if i.isdigit()]
numbers

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [39]:
mystr = "One 1 two 2 three 3 four 4 five 5 six 6789"
numbers = [i for i in mystr if i.isalpha()]
print(numbers, end= '  ')

['O', 'n', 'e', 't', 'w', 'o', 't', 'h', 'r', 'e', 'e', 'f', 'o', 'u', 'r', 'f', 'i', 'v', 'e', 's', 'i', 'x']  

In [40]:
list5 = [s.upper() for s in "Hello World"]
list5

['H', 'E', 'L', 'L', 'O', ' ', 'W', 'O', 'R', 'L', 'D']

In [41]:
list6 = [w.strip(',') for w in ['these,', 'words,,', 'mostly', 'have, commas,']]
list6

['these', 'words', 'mostly', 'have, commas']

In [42]:
list7 = [x for x in 'apple' if x in 'aeiou' else '*']
list7

SyntaxError: invalid syntax (<ipython-input-42-78fd72f56cda>, line 1)

In [43]:
list7 = [x if x in 'aeiou' else '*' for x in 'apple']
list7

['a', '*', '*', '*', 'e']

In [46]:
list8 = [x.sort() for x in [[2,1], [4,3], [0,1]]]
list8

[None, None, None]

In [47]:
list8 = [sorted(x) for x in [[2,1], [4,3], [0,1]]]
list8

[[1, 2], [3, 4], [0, 1]]

In [50]:
list9 = [print(x) for x in (1,2,3)] 
list9

1
2
3


[None, None, None]

In [51]:
for x in (1,2,3):
    print(x)

1
2
3


In [52]:
from random import randrange
list10 = [randrange(1,7) for _ in range(10)]
list10

[5, 6, 5, 5, 1, 2, 1, 2, 3, 4]

In [53]:
a = [x if x % 2 == 0 else None for x in range(10)]
a

[0, None, 2, None, 4, None, 6, None, 8, None]

In [54]:
b = [2 * (x if x % 2 == 0 else -1) + 1 for x in range(10)]
b

[1, -1, 5, -1, 9, -1, 13, -1, 17, -1]

In [55]:
numbers = []
for x in range(10):
    if x % 2 == 0:
        temp = x
    else:
        temp = -1
    numbers.append(2 * temp + 1)
print(numbers)

[1, -1, 5, -1, 9, -1, 13, -1, 17, -1]


In [56]:
c = [x if x > 2 else '*' for x in range(10) if x % 2 == 0]
c

['*', '*', 4, 6, 8]

In [58]:
d = [x if (x > 2 and x % 2 == 0) else '*' for x in range(10)]
d

['*', '*', '*', '*', 4, '*', 6, '*', 8, '*']

In [59]:
import numpy as np

x = np.arange(9)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
x = np.arange(16).reshape((4,4))

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [66]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])